# Generated by Django 6.1 on 2026-08-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('system', models.CharField(choices=[('PLTS', 'PLTS'), ('PLTB', 'PLTB')], max_length=10)),
                ('voltage', models.FloatField(default=0)),
                ('current', models.FloatField(default=0)),
                ('power', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
