# Generated by Django 6.1 on 2026-08-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='soc',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='system',
            field=models.CharField(choices=[('PLTS', 'PLTS'), ('PLTB', 'PLTB'), ('BATTERY', 'BATTERY')], max_length=10),
        ),
    ]
